ports:
  # Sonarqube port
  - port: 9000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - SonarSource.sonarlint-vscode
    - ms-python.python
    - eamodio.gitlens
    - redhat.java
    - wesleyegberto.vscode-java-tests
    - magicstack.MagicPython
    - ms-azuretools.vscode-docker
