tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
      
ports:
  # Sonarqube port
  - port: 9000
    onOpen: open-preview

vscode:
  extensions:
    - SonarSource.sonarlint-vscode
    - ms-python.python
    - eamodio.gitlens
    - redhat.java
    - wesleyegberto.vscode-java-tests
    - magicstack.MagicPython
    - ms-azuretools.vscode-docker
