ports:
  - port: 9000
    onOpen: open-preview

vscode:
  extensions:
    - SonarSource.sonarlint-vscode
    - ms-python.python
    - eamodio.gitlens
    - redhat.java
    - wesleyegberto.vscode-java-tests
    - magicstack.MagicPython
    - ms-azuretools.vscode-docker
    - ms-toolsai.vscode-jupyter-cell-tags
